language: ruby
script: "script/test_all"
bundler_args: "--standalone --binstubs --without documentation"
sudo: false
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ree
  - jruby-19mode
  - jruby-18mode
env:
  - BRANCH=master
  - BRANCH=2-99-maintenance
