language: ruby
script: "script/test_all"
bundler_args: "--standalone --binstubs --without documentation"
sudo: false
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.3.3
  - 2.2.5
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - jruby
env:
  - BRANCH=master
  - BRANCH=2-99-maintenance
matrix:
  include:
    - rvm: jruby-1.7.27
      env:
        - JRUBY_OPTS='--dev'
        - BRANCH=master
    - rvm: jruby-1.7.27
      env:
        - JRUBY_OPTS='--dev'
        - BRANCH=2-99-maintenance
    - rvm: jruby-1.7.27
      env:
        - JRUBY_OPTS='--dev --1.8'
        - BRANCH=master
    - rvm: jruby-1.7.27
      env:
        - JRUBY_OPTS='--dev --1.8'
        - BRANCH=2-99-maintenance
